// ... existing imports ...
const expenseRoutes = require('./routes/expenses'); // <--- ADD THIS

// ... inside middleware ...
app.use(express.json());
app.use(cors());

// ... Routes ...
app.use('/api/expenses', expenseRoutes); // <--- ADD THIS

// ... existing connection code ...